version: "3"
services: 
 db: 
  image: mysql:5.7
  env_file: .env
 web: 
  build: 
   context: .
  depends_on: 
   - db 
  env_file: .env
  command: python manage.py runserver 0.0.0.0:8000
  volumes: 
   - .:/webapp
  ports: 
   - "8000:8000"

